[tool.poetry]
name = "1cv8-mgmt-tool"
version = "2022.05.15"
description = ""
authors = ["Ilya Bogdanov <zeerayne1337@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pywin32 = [
    { version = "^304", platform = "win32" },
]
aioboto3 = "^9.6.0"
filechunkio = "^1.8"
aioshutil = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
