[tool.poetry]
name = "1cv8-mgmt-tool"
version = "2022.05.15"
description = ""
authors = ["Ilya Bogdanov <zeerayne1337@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pywin32 = [
    { version = "^304", platform = "win32" },
]
aioboto3 = "^9.6.0"
filechunkio = "^1.8"
aioshutil = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-spec = "^3.2.0"
pytest-mock = "^3.7.0"

[tool.pytest.ini_options]
spec_header_format = "Case: {test_case}\nPath: {module_path}"
spec_test_format = '{result} {docstring_summary}'
spec_success_indicator = '✓'
spec_failure_indicator = '✗'
spec_skipped_indicator = '↷'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
