[tool.poetry]
name = "1cv8-mgmt-tool"
version = "2022.05.15"
description = ""
authors = ["Ilya Bogdanov <zeerayne1337@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pywin32 = [
    { version = "^304", platform = "win32" },
]
aioboto3 = "^9.6.0"
filechunkio = "^1.8"
aioshutil = "^1.1"
aiofiles = "^0.8.0"
packaging = "^21.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-spec = "^3.2.0"
pytest-mock = "^3.7.0"
pytest-asyncio = "^0.18.3"
pytest-freezegun = "^0.4.2"
pytest-env = "^0.6.2"
yapf = "^0.32.0"
isort = "^5.10.1"
toml = "^0.10.2"
pre-commit = "^2.19.0"

[tool.pytest.ini_options]
spec_header_format = "Case: {test_case}\nPath: {module_path}"
spec_test_format = '{result} {docstring_summary}'
spec_success_indicator = '✓'
spec_failure_indicator = '✗'
spec_skipped_indicator = '↷'
asyncio_mode = 'auto'
env = """
    PYTHONPATH=.
    1CV8MGMT_SETTINGS_MODULE=tests.settings
    """

[tool.isort]
combine_as_imports = true
extra_standard_library = "packaging"
group_by_package = true
known_pytest = [
    "pytest",
    "pytest_mock",
]
line_length = 120
lines_after_imports = 2
multi_line_output = 5
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "PYTEST",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

[tool.yapf]
based_on_style = "pep8"
blank_lines_between_top_level_imports_and_variables = 2
blank_lines_around_top_level_definition = 2
coalesce_brackets = true
column_limit = 120
dedent_closing_brackets = true
spaces_around_power_operator = true
spaces_before_comment = 2
space_between_ending_comma_and_closing_bracket = true
split_before_logical_operator = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
