[project]
name = "1cv8-mgmt-tool"
version = "2026.08.04"
description = ""
authors = [{ name = "Ilya Bogdanov", email = "zeerayne1337@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "aioboto3>=15.0.0,<16",
    "filechunkio>=1.8,<2",
    "aioshutil>=1.6,<2",
    "aiofiles>=25.0.0,<26",
    "packaging",
    "asyncpg",
    "pywin32>=312,<313; sys_platform == 'win32'",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0,<10",
    "pytest-spec>=5.0.0,<6",
    "pytest-mock>=3.0.0,<4",
    "pytest-asyncio>=1.3.0,<2",
    "pytest-env>=1.0.0,<2",
    "pytest-freezer>=0.4.9,<1",
    "pre-commit>=4.0.0,<5",
    "coveralls>=4.0.0,<5",
    "coverage>=7,<8",
    "ruff",
]
debug = [
    "debugpy>=1.6.6",
]

[tool.pytest.ini_options]
spec_header_format = "Case: {test_case}\nPath: {module_path}"
spec_test_format = '{result} {docstring_summary}'
spec_success_indicator = '✓'
spec_failure_indicator = '✗'
spec_skipped_indicator = '↷'
asyncio_mode = 'auto'
env = """
    PYTHONPATH=.
    1CV8MGMT_SETTINGS_MODULE=tests.settings
    """

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "W", "Q"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"surrogate/tests/test_surrogate.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
