# This workflow will check modified files with flake8

name: flake8
on: [push]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
      - name: Install dependencies
        run: make install-dev
      - name: Get changed python source files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            *.py
      - name: Check code with flake8
        if: steps.changed-files.outputs.any_changed == 'true'
        run: poetry run flake8 ${{ steps.changed-files.outputs.all_changed_files }}
